<a href="https://colab.research.google.com/github/nitishpanda666/python_assignment1/blob/main/assignmet5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import numpy as np

In [7]:
df=pd.read_csv("/student-mat.csv",sep=";")

In [8]:
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [11]:
display(df.head(10))

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,12,12,11
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,6,6,5,6
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,14,15,15

In [13]:
missingvalues=df.isnull().sum()

In [14]:
missingvalues[missingvalues>0]

Series([], dtype: int64)

In [16]:
numerical_df=df.select_dtypes(include=[np.number])
covariance_matrix=numerical_df.cov()
display(covariance_matrix)

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
age,1.628285,-0.228619,-0.226949,0.062873,-0.004434,0.231221,0.061717,0.020947,0.180364,0.149039,0.192733,-0.110326,1.789501,-0.271413,-0.688653,-0.944612
Medu,-0.228619,1.198445,0.742717,-0.131061,0.059667,-0.192681,-0.003842,0.033779,0.078115,0.019341,-0.066440,-0.071349,0.878622,0.746135,0.887509,1.089096
Fedu,-0.226949,0.742717,1.184180,-0.120073,-0.008379,-0.202641,-0.001337,-0.013963,0.052220,0.002313,-0.017702,0.022303,0.213134,0.687245,0.674953,0.760078
traveltime,0.062873,-0.131061,-0.120073,0.486513,-0.059070,0.047844,-0.010512,-0.011861,0.022162,0.085941,0.120478,0.007274,-0.072255,-0.215402,-0.401940,-0.374337
studytime,-0.004434,0.059667,-0.008379,-0.059070,0.704324,-0.108321,0.029898,-0.120041,-0.059706,-0.146533,-0.274304,-0.088228,-0.421127,0.447401,0.428947,0.376110
failures,0.231221,-0.192681,-0.202641,0.047844,-0.108321,0.553017,-0.029564,0.068329,0.103123,0.090118,0.135964,0.068059,0.379265,-0.875557,-0.995528,-1.227932
famrel,0.061717,-0.003842,-0.001337,-0.010512,0.029898,-0.029564,0.803997,0.134974,0.064454,-0.061974,-0.130952,0.117252,-0.318287,0.065977,-0.061659,0.211000
freetime,0.020947,0.033779,-0.013963,-0.011861,-0.120041,0.068329,0.134974,0.997725,0.316944,0.185954,0.190163,0.105173,-0.464274,0.041817,-0.051764,0.051745
goout,0.180364,0.078115,0.052220,0.022162,-0.059706,0.103123,0.064454,0.316944,1.239388,0.264763,0.602744,-0.014824,0.394718,-0.550967,-0.679438,-0.677292
Dalc,0.149039,0.019341,0.002313,0.085941,-0.146533,0.090118,-0.061974,0.185954,0.264763,0.793420,0.742852,0.095579,0.797758,-0.278385,-0.214836,-0.223061
Walc,0.192733,-0.066440,-0.017702,0.120478,-0.274304,0.135964,-0.130952,0.190163,0.602744,0.742852,1.658678,0.165585,1.404774,-0.539388,-0.411425,-0.306464
health,-0.110326,-0.071349,0.022303,0.007274,-0.088228,0.068059,0.117252,0.105173,-0.014824,0.095579,0.165585,1.932944,-0.333098,-0.337666,-0.511039,-0.390677
absences,1.789501,0.878622,0.213134,-0.072255,-0.421127,0.379265,-0.318287,-0.464274,0.394718,0.797758,1.404774,-0.333098,64.049541,-0.823556,-0.956596,1.255703
G1,-0.271413,0.746135,0.687245,-0.215402,0.447401,-0.875557,0.065977,0.041817,-0.550967,-0.278385,-0.539388,-0.337666,-0.823556,11.017053,10.638836,12.187682
G2,-0.688653,0.887509,0.674953,-0.401940,0.428947,-0.995528,-0.061659,-0.051764,-0.679438,-0.214836,-0.411425,-0.511039,-0.956596,10.638836,14.148917,15.593697
G3,-0.944612,1.089096,0.760078,-0.374337,0.376110,-1.227932,0.211000,0.051745,-0.677292,-0.223061,-0.306464,-0.390677,1.255703,12.187682,15.593697,20.989616

In [19]:
correlation_matrix = numerical_df.corr()
display(correlation_matrix)

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
age,1.000000,-0.163658,-0.163438,0.070641,-0.004140,0.243665,0.053940,0.016434,0.126964,0.131125,0.117276,-0.062187,0.175230,-0.064081,-0.143474,-0.161579
Medu,-0.163658,1.000000,0.623455,-0.171639,0.064944,-0.236680,-0.003914,0.030891,0.064094,0.019834,-0.047123,-0.046878,0.100285,0.205341,0.215527,0.217147
Fedu,-0.163438,0.623455,1.000000,-0.158194,-0.009175,-0.250408,-0.001370,-0.012846,0.043105,0.002386,-0.012631,0.014742,0.024473,0.190270,0.164893,0.152457
traveltime,0.070641,-0.171639,-0.158194,1.000000,-0.100909,0.092239,-0.016808,-0.017025,0.028540,0.138325,0.134116,0.007501,-0.012944,-0.093040,-0.153198,-0.117142
studytime,-0.004140,0.064944,-0.009175,-0.100909,1.000000,-0.173563,0.039731,-0.143198,-0.063904,-0.196019,-0.253785,-0.075616,-0.062700,0.160612,0.135880,0.097820
failures,0.243665,-0.236680,-0.250408,0.092239,-0.173563,1.000000,-0.044337,0.091987,0.124561,0.136047,0.141962,0.065827,0.063726,-0.354718,-0.355896,-0.360415
famrel,0.053940,-0.003914,-0.001370,-0.016808,0.039731,-0.044337,1.000000,0.150701,0.064568,-0.077594,-0.113397,0.094056,-0.044354,0.022168,-0.018281,0.051363
freetime,0.016434,0.030891,-0.012846,-0.017025,-0.143198,0.091987,0.150701,1.000000,0.285019,0.209001,0.147822,0.075733,-0.058078,0.012613,-0.013777,0.011307
goout,0.126964,0.064094,0.043105,0.028540,-0.063904,0.124561,0.064568,0.285019,1.000000,0.266994,0.420386,-0.009577,0.044302,-0.149104,-0.162250,-0.132791
Dalc,0.131125,0.019834,0.002386,0.138325,-0.196019,0.136047,-0.077594,0.209001,0.266994,1.000000,0.647544,0.077180,0.111908,-0.094159,-0.064120,-0.054660
Walc,0.117276,-0.047123,-0.012631,0.134116,-0.253785,0.141962,-0.113397,0.147822,0.420386,0.647544,1.000000,0.092476,0.136291,-0.126179,-0.084927,-0.051939
health,-0.062187,-0.046878,0.014742,0.007501,-0.075616,0.065827,0.094056,0.075733,-0.009577,0.077180,0.092476,1.000000,-0.029937,-0.073172,-0.097720,-0.061335
absences,0.175230,0.100285,0.024473,-0.012944,-0.062700,0.063726,-0.044354,-0.058078,0.044302,0.111908,0.136291,-0.029937,1.000000,-0.031003,-0.031777,0.034247
G1,-0.064081,0.205341,0.190270,-0.093040,0.160612,-0.354718,0.022168,0.012613,-0.149104,-0.094159,-0.126179,-0.073172,-0.031003,1.000000,0.852118,0.801468
G2,-0.143474,0.215527,0.164893,-0.153198,0.135880,-0.355896,-0.018281,-0.013777,-0.162250,-0.064120,-0.084927,-0.097720,-0.031777,0.852118,1.000000,0.904868
G3,-0.161579,0.217147,0.152457,-0.117142,0.097820,-0.360415,0.051363,0.011307,-0.132791,-0.054660,-0.051939,-0.061335,0.034247,0.801468,0.904868,1.000000